#!/bin/bash
# save-outputs.sh — Run this ONCE after "terraform apply" to save all outputs to ~/loganalyzer.env
# Usage: bash terraform/scripts/save-outputs.sh
# Then each new terminal: source ~/loganalyzer.env

set -euo pipefail

TERRAFORM_DIR="$(cd "$(dirname "$0")/.." && pwd)"
ENV_FILE="$HOME/loganalyzer.env"

echo "Reading Terraform outputs from: $TERRAFORM_DIR"
cd "$TERRAFORM_DIR"

# Verify terraform state exists
if [ ! -f "terraform.tfstate" ]; then
  echo "ERROR: terraform.tfstate not found. Run 'terraform apply' first."
  exit 1
fi

# Read all outputs
BASTION_IP=$(terraform output -raw bastion_public_ip)
MASTER_IP=$(terraform output -raw k8s_master_private_ip)
WORKER_IPS=$(terraform output -json k8s_worker_private_ips | tr -d '[]"' | tr ',' ' ')
ECR_BACKEND=$(terraform output -raw ecr_backend_url)
ECR_FRONTEND=$(terraform output -raw ecr_frontend_url)
S3_BUCKET=$(terraform output -raw s3_log_archive_bucket)
AWS_ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
ECR_REGISTRY="${AWS_ACCOUNT_ID}.dkr.ecr.ap-southeast-1.amazonaws.com"
SSH_KEY="$HOME/.ssh/loganalyzer-key.pem"

# Write to env file
cat > "$ENV_FILE" << EOF
# LogAnalyzer Environment Variables
# Generated by: bash terraform/scripts/save-outputs.sh
# Generated at: $(date)
# Load with: source ~/loganalyzer.env

# AWS
export AWS_ACCOUNT_ID="${AWS_ACCOUNT_ID}"
export AWS_REGION="ap-southeast-1"
export ECR_REGISTRY="${ECR_REGISTRY}"

# EC2 Instances
export BASTION_IP="${BASTION_IP}"
export MASTER_IP="${MASTER_IP}"
export WORKER_IPS="${WORKER_IPS}"
export SSH_KEY="${SSH_KEY}"

# ECR URLs (use in values.yaml and GitHub Actions)
export ECR_BACKEND="${ECR_BACKEND}"
export ECR_FRONTEND="${ECR_FRONTEND}"

# S3
export S3_BUCKET="${S3_BUCKET}"

# Shortcuts
alias ssh-bastion="ssh -i \$SSH_KEY ubuntu@\$BASTION_IP"
alias ssh-master="ssh -J ubuntu@\$BASTION_IP ubuntu@\$MASTER_IP -i \$SSH_KEY"
alias k="kubectl"
alias kn="kubectl -n loganalyzer"
EOF

echo ""
echo "✅ Saved to: $ENV_FILE"
echo ""
echo "Summary:"
echo "  Bastion IP : $BASTION_IP"
echo "  Master IP  : $MASTER_IP"
echo "  Worker IPs : $WORKER_IPS"
echo "  ECR Backend: $ECR_BACKEND"
echo "  S3 Bucket  : $S3_BUCKET"
echo ""
echo "Run this to load variables into current terminal:"
echo "  source ~/loganalyzer.env"
echo ""
echo "Add to ~/.bashrc to auto-load every terminal:"
echo "  echo 'source ~/loganalyzer.env' >> ~/.bashrc"
